def retList(dataset,
            bdbMode=None,
            sensorSelect=False):

    """
    Function to return list of embedding file paths and dataset names

    INPUTS:-
    1) dataset: Name of the dataset
    2) bdbMode: Sensor mode for behavePassDB dataset
    3) sensorSelect: If True, then list returned for sensor selection simulation

    OUTPUTS:-
    1) embedding_list: List containing embedding file paths
    2) dataset_list: List containing name of the datasets
    """
    if(sensorSelect == False):

        if(dataset == 'soli'):
            embedding_list = ['./Embeddings/DGBQA_CGID_Res3D-ViViT_pt5-pt5_SOLI.npz',
                                './Embeddings/DGBQA_CGID_Res3D-ViViT_pt5-1_SOLI.npz',
                                './Embeddings/DGBQA_CGID_Res3D-ViViT_pt5-1pt5_SOLI.npz',
                                './Embeddings/DGBQA_CGID_Res3D-ViViT_1-pt5_SOLI.npz',
                                './Embeddings/DGBQA_CGID_Res3D-ViViT_1-1_SOLI.npz',
                                './Embeddings/DGBQA_CGID_Res3D-ViViT_1-1pt5_SOLI.npz',
                                './Embeddings/DGBQA_CGID_Res3D-ViViT_1pt5-pt5_SOLI.npz',
                                './Embeddings/DGBQA_CGID_Res3D-ViViT_1pt5-1_SOLI.npz',
                                './Embeddings/DGBQA_CGID_Res3D-ViViT_1pt5-1pt5_SOLI.npz',
                                './Embeddings/DGBQA_CGID_Res3D-MF_pt5-pt5_SOLI.npz',
                                './Embeddings/DGBQA_CGID_Res3D-MF_pt5-1_SOLI.npz',
                                './Embeddings/DGBQA_CGID_Res3D-MF_pt5-1pt5_SOLI.npz',
                                './Embeddings/DGBQA_CGID_Res3D-MF_1-pt5_SOLI.npz',
                                './Embeddings/DGBQA_CGID_Res3D-MF_1-1_SOLI.npz',
                                './Embeddings/DGBQA_CGID_Res3D-MF_1-1pt5_SOLI.npz',
                                './Embeddings/DGBQA_CGID_Res3D-MF_1pt5-pt5_SOLI.npz',
                                './Embeddings/DGBQA_CGID_Res3D-MF_1pt5-1_SOLI.npz',
                                './Embeddings/DGBQA_CGID_Res3D-MF_1pt5-1pt5_SOLI.npz',
                                './Embeddings/MS_TPN_pt5-pt5_SOLI.npz',
                                './Embeddings/MS_TPN_pt5-1_SOLI.npz',
                                './Embeddings/MS_TPN_pt5-1pt5_SOLI.npz',
                                './Embeddings/MS_TPN_1-pt5_SOLI.npz',
                                './Embeddings/MS_TPN_1-1_SOLI.npz',
                                './Embeddings/MS_TPN_1-1pt5_SOLI.npz',
                                './Embeddings/MS_TPN_1pt5-pt5_SOLI.npz',
                                './Embeddings/MS_TPN_1pt5-1_SOLI.npz',
                                './Embeddings/MS_TPN_1pt5-1pt5_SOLI.npz',
                                './Embeddings/MS_TAM_pt5-pt5_SOLI.npz',
                                './Embeddings/MS_TAM_1-pt5_SOLI.npz',
                                './Embeddings/MS_TAM_1-1_SOLI.npz',
                                './Embeddings/MS_MViT_pt5-pt5_SOLI.npz',
                                './Embeddings/MS_MViT_pt5-1_SOLI.npz',
                                './Embeddings/MS_MViT_pt5-1pt5_SOLI.npz',
                                './Embeddings/MS_MViT_1-pt5_SOLI.npz',
                                './Embeddings/MS_MViT_1-1_SOLI.npz',
                                './Embeddings/MS_MViT_1-1pt5_SOLI.npz',
                                './Embeddings/MS_MViT_1pt5-pt5_SOLI.npz',
                                './Embeddings/MS_MViT_1pt5-1_SOLI.npz',
                                './Embeddings/MS_MViT_1pt5-1pt5_SOLI.npz']
            dataset_list = ['Soli']*39


        if(dataset == 'handlogin'):
            embedding_list = ['./Embeddings/MS_ViViT_pt5-pt5_HandLogin.npz',
                            './Embeddings/MS_ViViT_pt5-1_HandLogin.npz',
                            './Embeddings/MS_ViViT_pt5-1pt5_HandLogin.npz',
                            './Embeddings/MS_ViViT_pt5-2pt5_HandLogin.npz',
                            './Embeddings/MS_ViViT_1-pt5_HandLogin.npz',
                            './Embeddings/MS_ViViT_1-1_HandLogin.npz',
                            './Embeddings/MS_ViViT_1-1pt5_HandLogin.npz',
                            './Embeddings/MS_ViViT_1-2pt5_HandLogin.npz',
                            './Embeddings/MS_ViViT_1pt5-pt5_HandLogin.npz',
                            './Embeddings/MS_ViViT_1pt5-1_HandLogin.npz',
                            './Embeddings/MS_ViViT_1pt5-1pt5_HandLogin.npz',
                            './Embeddings/MS_ViViT_1pt5-2pt5_HandLogin.npz',
                            './Embeddings/Test/DGBQA_CGID_Res3D-MF_1-pt5_HandLogin.npz',
                            './Embeddings/Test/DGBQA_CGID_Res3D-MF_1-1_HandLogin.npz',
                            './Embeddings/Test/DGBQA_CGID_Res3D-MF_1-1pt5_HandLogin.npz',
                            './Embeddings/Test/DGBQA_CGID_Res3D-MF_1-2pt5_HandLogin.npz',
                            './Embeddings/Test/DGBQA_CGID_Res3D-MF_1pt5-pt5_HandLogin.npz',
                            './Embeddings/Test/DGBQA_CGID_Res3D-MF_1pt5-1_HandLogin.npz',
                            './Embeddings/Test/DGBQA_CGID_Res3D-MF_1pt5-1pt5_HandLogin.npz',
                            './Embeddings/Test/DGBQA_CGID_Res3D-MF_1pt5-2pt5_HandLogin.npz',
                            './Embeddings/MS_TPN_pt5-pt5_HandLogin.npz',
                            './Embeddings/MS_TPN_pt5-1_HandLogin.npz',
                            './Embeddings/MS_TPN_pt5-1pt5_HandLogin.npz',
                            './Embeddings/MS_TPN_pt5-2pt5_HandLogin.npz',
                            './Embeddings/MS_TPN_1-pt5_HandLogin.npz',
                            './Embeddings/MS_TPN_1-1pt5_HandLogin.npz',
                            './Embeddings/MS_TPN_1-2pt5_HandLogin.npz',
                            './Embeddings/MS_TPN_1pt5-pt5_HandLogin.npz',
                            './Embeddings/MS_TPN_1pt5-1_HandLogin.npz',
                            './Embeddings/MS_TPN_1pt5-1pt5_HandLogin.npz',
                            './Embeddings/MS_TPN_1pt5-2pt5_HandLogin.npz',
                            './Embeddings/MS_TAM_pt5-pt5_HandLogin.npz',
                            './Embeddings/MS_TAM_pt5-1_HandLogin.npz',
                            './Embeddings/MS_TAM_pt5-1pt5_HandLogin.npz',
                            './Embeddings/MS_TAM_pt5-2pt5_HandLogin.npz',
                            './Embeddings/MS_TAM_1-pt5_HandLogin.npz',
                            './Embeddings/MS_TAM_1-1_HandLogin.npz',
                            './Embeddings/MS_TAM_1-1pt5_HandLogin.npz',
                            './Embeddings/MS_TAM_1-2pt5_HandLogin.npz',
                            './Embeddings/MS_TAM_1pt5-pt5_HandLogin.npz',
                            './Embeddings/MS_TAM_1pt5-1_HandLogin.npz',
                            './Embeddings/MS_TAM_1pt5-1pt5_HandLogin.npz',
                            './Embeddings/MS_TAM_1pt5-2pt5_HandLogin.npz',
                            './Embeddings/MS_MViT_pt5-pt5_HandLogin.npz',
                            './Embeddings/MS_MViT_pt5-1_HandLogin.npz',
                            './Embeddings/MS_MViT_pt5-1pt5_HandLogin.npz',
                            './Embeddings/MS_MViT_pt5-2pt5_HandLogin.npz',
                            './Embeddings/MS_MViT_1-pt5_HandLogin.npz',
                            './Embeddings/MS_MViT_1-1_HandLogin.npz',
                            './Embeddings/MS_MViT_1-1pt5_HandLogin.npz',
                            './Embeddings/MS_MViT_1-2pt5_HandLogin.npz',
                            './Embeddings/MS_MViT_1pt5-pt5_HandLogin.npz',
                            './Embeddings/MS_MViT_1pt5-1_HandLogin.npz',
                            './Embeddings/MS_MViT_1pt5-1pt5_HandLogin.npz',
                            './Embeddings/MS_MViT_1pt5-2pt5_HandLogin.npz']
            dataset_list = ['HandLogin']*55


        if(dataset == 'tiny'):
            embedding_list = ['./Embeddings/DGBQA_CGID_Res3D-ViViT_pt5-1_Tiny.npz',
                            './Embeddings/DGBQA_CGID_Res3D-ViViT_pt5-1pt5_Tiny.npz',
                            './Embeddings/DGBQA_CGID_Res3D-ViViT_pt5-2pt5_Tiny.npz',
                            './Embeddings/DGBQA_CGID_Res3D-ViViT_1-1_Tiny.npz',
                            './Embeddings/DGBQA_CGID_Res3D-ViViT_1-1pt5_Tiny.npz',
                            './Embeddings/DGBQA_CGID_Res3D-ViViT_1-2pt5_Tiny.npz',
                            './Embeddings/MS_MF_1-1_Tiny.npz',
                            './Embeddings/MS_MF_1-1pt5_Tiny.npz',
                            './Embeddings/MS_MF_1-2pt5_Tiny.npz',
                            './Embeddings/MS_TAM_1-1_Tiny.npz',
                            './Embeddings/MS_TAM_1-1pt5_Tiny.npz',
                            './Embeddings/MS_TAM_1-2pt5_Tiny.npz']
            dataset_list = ['Tiny']*12


        if(dataset == 'scut'):
            embedding_list = ['./Embeddings/scut/ms_mvit_pt5-pt01_scut.npz',
                            './Embeddings/scut/ms_mvit_pt5-pt05_scut.npz',
                            './Embeddings/scut/ms_mvit_pt5-pt5_scut.npz',
                            './Embeddings/scut/ms_mvit_pt5-1_scut.npz',
                            './Embeddings/scut/ms_mvit_pt5-pt5_scut.npz',
                            './Embeddings/scut/ms_mvit_1-pt01_scut.npz',
                            './Embeddings/scut/ms_mvit_1-pt05_scut.npz',
                            './Embeddings/scut/ms_mvit_1-pt5_scut.npz',
                            './Embeddings/scut/ms_mvit_1-1_scut.npz',
                            './Embeddings/scut/ms_mvit_1-pt5_scut.npz',
                            './Embeddings/scut/ms_mvit_1pt5-pt01_scut.npz',
                            './Embeddings/scut/ms_mvit_1pt5-pt05_scut.npz',
                            './Embeddings/scut/ms_mvit_1pt5-pt5_scut.npz',
                            './Embeddings/scut/ms_mvit_1pt5-1_scut.npz',
                            './Embeddings/scut/ms_mvit_1pt5-pt5_scut.npz',
                            './Embeddings/scut/ms_mf_pt5-pt01_scut.npz',
                            './Embeddings/scut/ms_mf_pt5-pt05_scut.npz',
                            './Embeddings/scut/ms_mf_pt5-pt5_scut.npz',
                            './Embeddings/scut/ms_mf_pt5-1_scut.npz',
                            './Embeddings/scut/ms_mf_pt5-pt5_scut.npz',
                            './Embeddings/scut/ms_mf_1-pt01_scut.npz',
                            './Embeddings/scut/ms_mf_1-pt05_scut.npz',
                            './Embeddings/scut/ms_mf_1-pt5_scut.npz',
                            './Embeddings/scut/ms_mf_1-1_scut.npz',
                            './Embeddings/scut/ms_mf_1-pt5_scut.npz',
                            './Embeddings/scut/ms_mf_1pt5-pt01_scut.npz',
                            './Embeddings/scut/ms_mf_1pt5-pt05_scut.npz',
                            './Embeddings/scut/ms_mf_1pt5-pt5_scut.npz',
                            './Embeddings/scut/ms_mf_1pt5-1_scut.npz',
                            './Embeddings/scut/ms_mf_1pt5-pt5_scut.npz',
                            './Embeddings/scut/ms_vivit_pt5-pt01_scut.npz',
                            './Embeddings/scut/ms_vivit_pt5-pt05_scut.npz',
                            './Embeddings/scut/ms_vivit_1-pt01_scut.npz',
                            './Embeddings/scut/ms_vivit_1-pt05_scut.npz',
                            './Embeddings/scut/ms_vivit_1pt5-pt01_scut.npz',
                            './Embeddings/scut/ms_vivit_1pt5-pt05_scut.npz',
                            './Embeddings/scut/DGBQA_CGID_Res3D-ViViT_1-pt5_SCUT.npz',
                            './Embeddings/scut/DGBQA_CGID_Res3D-ViViT_1-1_SCUT.npz',
                            './Embeddings/scut/DGBQA_CGID_Res3D-ViViT_1-1pt5_SCUT.npz',
                            './Embeddings/scut/DGBQA_CGID_Res3D-ViViT_1-2pt5_SCUT.npz',
                            './Embeddings/scut/DGBQA_CGID_Res3D-ViViT_1pt5-pt5_SCUT.npz',
                            './Embeddings/scut/DGBQA_CGID_Res3D-ViViT_1pt5-1_SCUT.npz',
                            './Embeddings/scut/DGBQA_CGID_Res3D-ViViT_1pt5-1pt5_SCUT.npz',
                            './Embeddings/scut/DGBQA_CGID_Res3D-ViViT_1pt5-2pt5_SCUT.npz',
                            ]
            dataset_list = ['scut']*len(embedding_list)


        if(dataset == 'bdb'):
            bdbModes = ['Acc','Gyro','Grav','Accl','Magn']
            embedding_list = ['./Embeddings/bdb/idf_vanilla_lgtranet_k3-5_1-pt5-pt1_sensor'+str(bdbMode)+'_bdb.npz',
                                './Embeddings/bdb/idf_vanilla_lgtranet_k3-5_1-pt5-pt5_sensor'+str(bdbMode)+'_bdb.npz',
                                './Embeddings/bdb/idf_vanilla_lgtranet_k3-5_1-pt5-1_sensor'+str(bdbMode)+'_bdb.npz',
                                './Embeddings/bdb/idf_vanilla_lgtranet_k3-5_1-pt5-1pt5_sensor'+str(bdbMode)+'_bdb.npz',
                                './Embeddings/bdb/idf_vanilla_lgtranet_k3-5_1-1-pt1_sensor'+str(bdbMode)+'_bdb.npz',
                                './Embeddings/bdb/idf_vanilla_lgtranet_k3-5_1-1-pt5_sensor'+str(bdbMode)+'_bdb.npz',
                                './Embeddings/bdb/idf_vanilla_lgtranet_k3-5_1-1-1_sensor'+str(bdbMode)+'_bdb.npz',
                                './Embeddings/bdb/idf_vanilla_lgtranet_k3-5_1-1-1pt5_sensor'+str(bdbMode)+'_bdb.npz',
                                './Embeddings/bdb/idf_vanilla_lgtranet_k3-5_1-1pt5-pt1_sensor'+str(bdbMode)+'_bdb.npz',
                                './Embeddings/bdb/idf_vanilla_lgtranet_k3-5_1-1pt5-pt5_sensor'+str(bdbMode)+'_bdb.npz',
                                './Embeddings/bdb/idf_vanilla_lgtranet_k3-5_1-1pt5-1_sensor'+str(bdbMode)+'_bdb.npz',
                                './Embeddings/bdb/idf_vanilla_lgtranet_k3-5_1-1pt5-1pt5_sensor'+str(bdbMode)+'_bdb.npz',
                                './Embeddings/bdb/idf_vanilla_lgtranet_k3-5_1-2-pt1_sensor'+str(bdbMode)+'_bdb.npz',
                                './Embeddings/bdb/idf_vanilla_lgtranet_k3-5_1-2-pt5_sensor'+str(bdbMode)+'_bdb.npz',
                                './Embeddings/bdb/idf_vanilla_lgtranet_k3-5_1-2-1_sensor'+str(bdbMode)+'_bdb.npz',
                                './Embeddings/bdb/idf_vanilla_lgtranet_k3-5_1-2-1pt5_sensor'+str(bdbMode)+'_bdb.npz',
                                './Embeddings/bdb/idf_vanilla_bdLSTM_1-pt5-pt1_sensor'+str(bdbMode)+'_bdb.npz',
                                './Embeddings/bdb/idf_vanilla_bdLSTM_1-pt5-pt5_sensor'+str(bdbMode)+'_bdb.npz',
                                './Embeddings/bdb/idf_vanilla_bdLSTM_1-pt5-1_sensor'+str(bdbMode)+'_bdb.npz',
                                './Embeddings/bdb/idf_vanilla_bdLSTM_1-pt5-1pt5_sensor'+str(bdbMode)+'_bdb.npz',
                                './Embeddings/bdb/idf_vanilla_bdLSTM_1-1-pt1_sensor'+str(bdbMode)+'_bdb.npz',
                                './Embeddings/bdb/idf_vanilla_bdLSTM_1-1-pt5_sensor'+str(bdbMode)+'_bdb.npz',
                                './Embeddings/bdb/idf_vanilla_bdLSTM_1-1-1_sensor'+str(bdbMode)+'_bdb.npz',
                                './Embeddings/bdb/idf_vanilla_bdLSTM_1-1-1pt5_sensor'+str(bdbMode)+'_bdb.npz',
                                './Embeddings/bdb/idf_vanilla_bdLSTM_1-1pt5-pt1_sensor'+str(bdbMode)+'_bdb.npz',
                                './Embeddings/bdb/idf_vanilla_bdLSTM_1-1pt5-pt5_sensor'+str(bdbMode)+'_bdb.npz',
                                './Embeddings/bdb/idf_vanilla_bdLSTM_1-1pt5-1_sensor'+str(bdbMode)+'_bdb.npz',
                                './Embeddings/bdb/idf_vanilla_bdLSTM_1-1pt5-1pt5_sensor'+str(bdbMode)+'_bdb.npz',
                                './Embeddings/bdb/idf_vanilla_bdLSTM_1-2-pt1_sensor'+str(bdbMode)+'_bdb.npz',
                                './Embeddings/bdb/idf_vanilla_bdLSTM_1-2-pt5_sensor'+str(bdbMode)+'_bdb.npz',
                                './Embeddings/bdb/idf_vanilla_bdLSTM_1-2-1_sensor'+str(bdbMode)+'_bdb.npz',
                                './Embeddings/bdb/idf_vanilla_bdLSTM_1-2-1pt5_sensor'+str(bdbMode)+'_bdb.npz',]
            dataset_list = ['bdb'+str(bdbMode)]*32


        if(dataset == 'ntu_60'):
            embedding_list = ['./Embeddings/ntu/ms_hcn_1-pt5-pt01-multiStepmin3_ntu60.npz',
                            './Embeddings/ntu/ms_hcn_1-pt5-pt05-multiStepmin3_ntu60.npz',
                            './Embeddings/ntu/ms_hcn_1-pt5-pt5-multiStepmin3_ntu60.npz',
                            './Embeddings/ntu/ms_hcn_1-pt5-1-multiStepmin3_ntu60.npz',
                            './Embeddings/ntu/ms_hcn_1-pt5-1pt5-multiStepmin3_ntu60.npz',
                            './Embeddings/ntu/ms_hcn_1-1-pt01-multiStepmin3_ntu60.npz',
                            './Embeddings/ntu/ms_hcn_1-1-pt05-multiStepmin3_ntu60.npz',
                            './Embeddings/ntu/ms_hcn_1-1-pt5-multiStepmin3_ntu60.npz',
                            './Embeddings/ntu/ms_hcn_1-1-1-multiStepmin3_ntu60.npz',
                            './Embeddings/ntu/ms_hcn_1-1-1pt5-multiStepmin3_ntu60.npz',
                            './Embeddings/ntu/ms_hcn_1-1pt5-pt01-multiStepmin3_ntu60.npz',
                            './Embeddings/ntu/ms_hcn_1-1pt5-pt05-multiStepmin3_ntu60.npz',
                            './Embeddings/ntu/ms_hcn_1-1pt5-pt5-multiStepmin3_ntu60.npz',
                            './Embeddings/ntu/ms_hcn_1-1pt5-1-multiStepmin3_ntu60.npz',
                            './Embeddings/ntu/ms_hcn_1-1pt5-1pt5-multiStepmin3_ntu60.npz',
                            './Embeddings/ntu/ms_hcn_1-2-pt01-multiStepmin3_ntu60.npz',
                            './Embeddings/ntu/ms_hcn_1-2-pt05-multiStepmin3_ntu60.npz',
                            './Embeddings/ntu/ms_hcn_1-2-pt5-multiStepmin3_ntu60.npz',
                            './Embeddings/ntu/ms_hcn_1-2-1-multiStepmin3_ntu60.npz',
                            './Embeddings/ntu/ms_hcn_1-2-1pt5-multiStepmin3_ntu60.npz',
                            './Embeddings/ntu/ms_skateformer_1-pt5-pt01-multiStepmin3_ntu60.npz',
                            './Embeddings/ntu/ms_skateformer_1-pt5-pt05-multiStepmin3_ntu60.npz',
                            './Embeddings/ntu/ms_skateformer_1-pt5-pt5-multiStepmin3_ntu60.npz',
                            './Embeddings/ntu/ms_skateformer_1-pt5-1-multiStepmin3_ntu60.npz',
                            './Embeddings/ntu/ms_skateformer_1-pt5-1pt5-multiStepmin3_ntu60.npz',
                            './Embeddings/ntu/ms_skateformer_1-1-pt01-multiStepmin3_ntu60.npz',
                            './Embeddings/ntu/ms_skateformer_1-1-pt05-multiStepmin3_ntu60.npz',
                            './Embeddings/ntu/ms_skateformer_1-1-pt5-multiStepmin3_ntu60.npz',
                            './Embeddings/ntu/ms_skateformer_1-1-1-multiStepmin3_ntu60.npz',
                            './Embeddings/ntu/ms_skateformer_1-1-1pt5-multiStepmin3_ntu60.npz',
                            './Embeddings/ntu/ms_skateformer_1-1pt5-pt01-multiStepmin3_ntu60.npz',
                            './Embeddings/ntu/ms_skateformer_1-1pt5-pt05-multiStepmin3_ntu60.npz',
                            './Embeddings/ntu/ms_skateformer_1-1pt5-pt5-multiStepmin3_ntu60.npz',
                            './Embeddings/ntu/ms_skateformer_1-1pt5-1-multiStepmin3_ntu60.npz',
                            './Embeddings/ntu/ms_skateformer_1-1pt5-1pt5-multiStepmin3_ntu60.npz',
                            './Embeddings/ntu/ms_skateformer_1-2-pt01-multiStepmin3_ntu60.npz',
                            './Embeddings/ntu/ms_skateformer_1-2-pt05-multiStepmin3_ntu60.npz',
                            './Embeddings/ntu/ms_skateformer_1-2-pt5-multiStepmin3_ntu60.npz',
                            './Embeddings/ntu/ms_skateformer_1-2-1-multiStepmin3_ntu60.npz',
                            './Embeddings/ntu/ms_skateformer_1-2-1pt5-multiStepmin3_ntu60.npz',]
            dataset_list = ['ntu_60']*40


        if(dataset == 'ntu_120'):
            embedding_list = ['./Embeddings/ntu/ms_hcn_1-pt5-pt01-multiStepmin3_ntu120.npz',
                                './Embeddings/ntu/ms_hcn_1-pt5-pt05-multiStepmin3_ntu120.npz',
                                './Embeddings/ntu/ms_hcn_1-pt5-pt5-multiStepmin3_ntu120.npz',
                                './Embeddings/ntu/ms_hcn_1-pt5-1-multiStepmin3_ntu120.npz',
                                './Embeddings/ntu/ms_hcn_1-pt5-1pt5-multiStepmin3_ntu120.npz',
                                './Embeddings/ntu/ms_hcn_1-1-pt01-multiStepmin3_ntu120.npz',
                                './Embeddings/ntu/ms_hcn_1-1-pt05-multiStepmin3_ntu120.npz',
                                './Embeddings/ntu/ms_hcn_1-1-pt5-multiStepmin3_ntu120.npz',
                                './Embeddings/ntu/ms_hcn_1-1-1-multiStepmin3_ntu120.npz',
                                './Embeddings/ntu/ms_hcn_1-1-1pt5-multiStepmin3_ntu120.npz',
                                './Embeddings/ntu/ms_hcn_1-1pt5-pt01-multiStepmin3_ntu120.npz',
                                './Embeddings/ntu/ms_hcn_1-1pt5-pt05-multiStepmin3_ntu120.npz',
                                './Embeddings/ntu/ms_hcn_1-1pt5-pt5-multiStepmin3_ntu120.npz',
                                './Embeddings/ntu/ms_hcn_1-1pt5-1-multiStepmin3_ntu120.npz',
                                './Embeddings/ntu/ms_hcn_1-1pt5-1pt5-multiStepmin3_ntu120.npz',
                                './Embeddings/ntu/ms_hcn_1-2-pt01-multiStepmin3_ntu120.npz',
                                './Embeddings/ntu/ms_hcn_1-2-pt05-multiStepmin3_ntu120.npz',
                                './Embeddings/ntu/ms_hcn_1-2-pt5-multiStepmin3_ntu120.npz',
                                './Embeddings/ntu/ms_hcn_1-2-1-multiStepmin3_ntu120.npz',
                                './Embeddings/ntu/ms_hcn_1-2-1pt5-multiStepmin3_ntu120.npz',
                                './Embeddings/ntu/ms_skateformer_1-pt5-pt01-multiStepmin3_ntu120.npz',
                                './Embeddings/ntu/ms_skateformer_1-pt5-pt05-multiStepmin3_ntu120.npz',
                                './Embeddings/ntu/ms_skateformer_1-pt5-pt5-multiStepmin3_ntu120.npz',
                                './Embeddings/ntu/ms_skateformer_1-pt5-1-multiStepmin3_ntu120.npz',
                                './Embeddings/ntu/ms_skateformer_1-pt5-1pt5-multiStepmin3_ntu120.npz',
                                './Embeddings/ntu/ms_skateformer_1-1-pt01-multiStepmin3_ntu120.npz',
                                './Embeddings/ntu/ms_skateformer_1-1-pt05-multiStepmin3_ntu120.npz',
                                './Embeddings/ntu/ms_skateformer_1-1-pt5-multiStepmin3_ntu120.npz',
                                './Embeddings/ntu/ms_skateformer_1-1-1-multiStepmin3_ntu120.npz',
                                './Embeddings/ntu/ms_skateformer_1-1-1pt5-multiStepmin3_ntu120.npz',
                                './Embeddings/ntu/ms_skateformer_1-1pt5-pt01-multiStepmin3_ntu120.npz',
                                './Embeddings/ntu/ms_skateformer_1-1pt5-pt05-multiStepmin3_ntu120.npz',
                                './Embeddings/ntu/ms_skateformer_1-1pt5-pt5-multiStepmin3_ntu120.npz',
                                './Embeddings/ntu/ms_skateformer_1-1pt5-1-multiStepmin3_ntu120.npz',
                                './Embeddings/ntu/ms_skateformer_1-1pt5-1pt5-multiStepmin3_ntu120.npz',
                                './Embeddings/ntu/ms_skateformer_1-2-pt01-multiStepmin3_ntu120.npz',
                                './Embeddings/ntu/ms_skateformer_1-2-pt05-multiStepmin3_ntu120.npz',
                                './Embeddings/ntu/ms_skateformer_1-2-pt5-multiStepmin3_ntu120.npz',
                                './Embeddings/ntu/ms_skateformer_1-2-1-multiStepmin3_ntu120.npz',
                                './Embeddings/ntu/ms_skateformer_1-2-1pt5-multiStepmin3_ntu120.npz']
            dataset_list = ['ntu_120']*40



    if(sensorSelect == True):

        if(dataset == 'soliTiny'):
            embedding_list = [['./Embeddings/MS_MViT_pt5-1_SOLI.npz',
                               './Embeddings/DGBQA_CGID_Res3D-ViViT_1pt5-pt5_SOLI.npz',
                               './Embeddings/DGBQA_CGID_Res3D-ViViT_1pt5-1_SOLI.npz'],
                              ['./Embeddings/MS_MF_1-1pt5_Tiny.npz',
                               './Embeddings/DGBQA_CGID_Res3D-ViViT_1-2pt5_Tiny.npz',
                               './Embeddings/DGBQA_CGID_Res3D-ViViT_pt5-2pt5_Tiny.npz']]
            dataset_list = [['Soli',
                             'Soli',
                             'Soli'],
                            ['Tiny',
                             'Tiny',
                             'Tiny']]

        if(dataset == 'bdb'):
            embedding_list = [['./Embeddings/bdb/idf_vanilla_lgtranet_k3-5_1-pt5-1_sensorAcc_bdb.npz',
                               './Embeddings/bdb/idf_vanilla_lgtranet_k3-5_1-pt5-pt5_sensorAcc_bdb.npz',
                               './Embeddings/bdb/idf_vanilla_bdLSTM_1-1pt5-pt1_sensorAcc_bdb.npz'],
                              ['./Embeddings/bdb/idf_vanilla_bdLSTM_1-1-1pt5_sensorGyro_bdb.npz',
                               './Embeddings/bdb/idf_vanilla_lgtranet_k3-5_1-1pt5-pt5_sensorGyro_bdb.npz',
                               './Embeddings/bdb/idf_vanilla_bdLSTM_1-pt5-pt5_sensorGyro_bdb.npz'],
                              ['./Embeddings/bdb/idf_vanilla_lgtranet_k3-5_1-1pt5-1_sensorGrav_bdb.npz',
                               './Embeddings/bdb/idf_vanilla_lgtranet_k3-5_1-pt5-pt1_sensorGrav_bdb.npz',
                               './Embeddings/bdb/idf_vanilla_bdLSTM_1-1pt5-pt1_sensorGrav_bdb.npz'],
                              ['./Embeddings/bdb/idf_vanilla_bdLSTM_1-1pt5-1_sensorAccl_bdb.npz',
                               './Embeddings/bdb/idf_vanilla_bdLSTM_1-1-pt1_sensorAccl_bdb.npz ',
                               './Embeddings/bdb/idf_vanilla_bdLSTM_1-pt5-1pt5_sensorAccl_bdb.npz'],
                              ['./Embeddings/bdb/idf_vanilla_lgtranet_k3-5_1-1-1_sensorMagn_bdb.npz',
                               './Embeddings/bdb/idf_vanilla_bdLSTM_1-1pt5-pt1_sensorMagn_bdb.npz',
                               './Embeddings/bdb/idf_vanilla_lgtranet_k3-5_1-2-1pt5_sensorMagn_bdb.npz']]
            dataset_list = [['bdbAcc',
                             'bdbAcc',
                             'bdbAcc'],
                            ['bdbGyro',
                             'bdbGyro',
                             'bdbGyro'],
                            ['bdbGrav',
                             'bdbGrav',
                             'bdbGrav'],
                            ['bdbAccl',
                             'bdbAccl',
                             'bdbAccl'],
                            ['bdbMagn',
                             'bdbMagn',
                             'bdbMagn']]
        
    return embedding_list, dataset_list